### ISSUE TITLE
Silkscreen mislabeled I2C pins

### ISSUE THREAD

**Issue by adamgarbo** [adafruit/Adafruit-ISM330DHCX-LIS3MDL-FeatherWing-PCB#1]
Hi folks,

A quick note that the SDA and SCL silkscreen labels are incorrectly swapped on this FeatherWing board.

Reported here: https://forums.adafruit.com/viewtopic.php?f=57&t=173318

Cheers,
Adam

**Comment by ladyada** [comment]
woops will fix on re-order!
