### ISSUE TITLE
High current consumption during power-down 

### ISSUE THREAD

**Issue by adamgarbo** [adafruit/Adafruit-ISM330DHCX-LIS3MDL-FeatherWing-PCB#2]
Hi folks,

There appears to be an issue with this FeatherWing having a high current consumption when in power-down mode. I'm currently measuring 0.82 mA using a Fluke 287 meter when both the LIS3MDL and ISM330DHCX are manually powered-down.

Related forum post (with code) here: https://forums.adafruit.com/viewtopic.php?f=57&t=173364

When I pull just the LIS3MDL's AD_M to GND, bypassing the 10 kΩ resistor, the power draw drops to ~136 uA. Are the I2C address pins supposed to draw several hundred microamps? 

The LIS3MDL and ISM330DHCX are rated as having quiescent draws of 1 µA and 3 µA, respectively, when in power-down mode. It'd be great to see the power efficiency of this board get closer to these figures. Could possible solutions include placing the I2C address resistors on the other side of the jumper and/or using a higher value resistor?

Cheers,
Adam

**Comment by ladyada** [comment]
hi yeah that sounds odd but we dont have any insight to the internals 
we can revise a future run to add another jumper...it may be a bit because we ordered PCBs recently and we dont sell a ton. for now we recommend soldering some wire to make a jumper!

**Comment by adamgarbo** [comment]
Thanks @ladyada!

I don't think the issue is related to the sensors themselves, but more the resistance values of the pull-down/up resistors. If I have time, I'll try to isolate where all the remaining draw is coming from and report back. No rush!

Cheers,
Adam
